export const SECURITY_TIPS = {
  safe: [
    "Verifica que el dominio coincida con el sitio que intentas visitar.",
    "Busca el protocolo HTTPS para asegurar que la conexión esté cifrada.",
    "Evita compartir información sensible si estás conectado a una red Wi-Fi pública.",
    "Mantener el navegador actualizado ayuda a protegerte contra vulnerabilidades conocidas.",
    "Considera el uso de un gestor de contraseñas para mejorar tu seguridad digital.",
    "Habilitar la autenticación de dos factores (2FA) añade una capa extra de protección.",
    "Desconfía de solicitudes de descarga automáticas al abrir un enlace.",
    "Revisar periódicamente los permisos del sitio puede prevenir accesos no deseados.",
    "Limpia las cookies del navegador para reducir el rastreo publicitario.",
    "Evita guardar claves bancarias en el autocompletado del sistema.",
    "Comprueba la validez del certificado de seguridad del sitio.",
    "Las extensiones de bloqueo de rastreadores pueden mejorar tu privacidad.",
    "Cierra la sesión al terminar en sitios que manejen datos personales.",
    "No compartas enlaces de acceso temporal con personas desconocidas.",
    "Un sistema operativo actualizado es la primera línea de defensa.",
    "Usa conexiones seguras o VPN cuando manejes datos empresariales o privados.",
    "Presta atención a las alertas de tu software de seguridad local.",
    "Errores gramaticales graves en el sitio pueden ser una señal de falta de autenticidad.",
    "Escribir la URL directamente es más seguro que hacer clic en enlaces de correos.",
    "Reporta cualquier comportamiento inusual que observes durante la navegación.",
  ],
  suspicious: [
    "El dominio presenta patrones inusuales; se recomienda precaución al navegar.",
    "Evita proporcionar datos financieros en sitios con nivel de riesgo moderado.",
    "La descarga de archivos desde este origen podría representar un riesgo potencial.",
    "Este sitio presenta características similares a páginas utilizadas para suplantación.",
    "Analiza si las promesas del sitio son coherentes con servicios oficiales.",
    "Evita vincular tus cuentas personales con sitios que no sean de total confianza.",
    "La reciente creación del dominio puede ser un indicador de baja reputación.",
    "La ausencia de políticas de privacidad claras suele ser una señal de alerta.",
    "Considera métodos de pago con protección al comprador en portales desconocidos.",
    "La publicidad excesiva puede ser utilizada para ocultar scripts de rastreo.",
    "Limita el acceso del sitio a tu ubicación o periféricos si no es estrictamente necesario.",
    "Busca referencias externas sobre la reputación de este dominio.",
    "Solicitudes de actualización de software inesperadas pueden ser engañosas.",
    "Inconsistencias en el diseño visual podrían indicar un sitio no oficial.",
    "Cierra formularios que soliciten datos de contacto sin una justificación clara.",
    "Navegar en modo incógnito puede limitar la exposición de tus datos locales.",
    "Desconfía de asistentes de soporte que soliciten control remoto de tu equipo.",
    "Los enlaces acortados a veces se utilizan para ocultar el destino final real.",
    "Respeta las advertencias de seguridad de tu navegador si bloquea el acceso.",
    "Considera no ingresar información de identidad en este enlace por prevención.",
  ],
  malicious: [
    "Múltiples motores de seguridad sugieren evitar la interacción con este sitio.",
    "Existe un riesgo potencial de ejecución de código no deseado al visitar el enlace.",
    "Se recomienda no introducir credenciales para prevenir posibles accesos no autorizados.",
    "Tu información de navegación podría estar expuesta a rastreadores de alta agresividad.",
    "Se han detectado comportamientos asociados a procesos que consumen recursos del sistema.",
    "Cerrar la pestaña ayuda a interrumpir cualquier comunicación activa con el servidor.",
    "Si descargaste contenido, se aconseja un análisis con software de seguridad actualizado.",
    "Un escaneo preventivo de tu dispositivo es una buena práctica tras visitar sitios de riesgo.",
    "Considera actualizar tus claves si crees haberlas expuesto en una sesión reciente.",
    "Este dominio figura en listas de bloqueo de diversas entidades de ciberseguridad.",
    "El certificado de seguridad podría estar comprometido o no ser válido.",
    "El sitio podría intentar aprovechar debilidades técnicas en navegadores antiguos.",
    "Evita conectar memorias USB si sospechas que tu equipo ha estado expuesto a riesgos.",
    "Puedes colaborar reportando el enlace en plataformas de seguridad ciudadana.",
    "Monitorea tus movimientos bancarios si has interactuado con el sitio por error.",
    "Desconectarse de la red temporalmente puede frenar procesos de transferencia de datos.",
    "La navegación en sitios marcados como peligrosos puede comprometer tu privacidad.",
    "La estructura del enlace sugiere posibles intentos de manipulación de datos.",
    "Ciertos scripts en este dominio podrían intentar acceder a información del portapapeles.",
    "Mantener un firewall activo ayuda a bloquear intentos de conexión sospechosos.",
  ],
};
